### ISSUE TITLE
Incorrect version strings on AmazonMQ

### ISSUE THREAD

**Issue by kisst** [awsdocs/amazon-mq-developer-guide#1]
https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/broker-engine.html suggest that the valid values are `ActiveMQ 5.15.8` and etc, while the API accept the short / number version only like `5.15.8` and etc, example error from CFN:
```
Broker engine version [ActiveMQ 5.15.8] is invalid for broker engine type [ACTIVEMQ].
Valid values: [5.15.8, 5.15.6, 5.15.0]. 
(Service: AmazonMQ; Status Code: 400; Error Code: BadRequestException; Request ID: ...
```
 based on this the [cfn-lint](https://github.com/awslabs/cfn-python-lint) project also mark all template invalid.
```
curl -s https://raw.githubusercontent.com/awslabs/cfn-python-lint/master/src/cfnlint/data/CloudSpecs/eu-west-1.json  | jq -r .ValueTypes.AmazonMQEngineVersion.AllowedValues[]
ActiveMQ 5.15.0
ActiveMQ 5.15.6
ActiveMQ 5.15.8
```
Before raising this as an issue there, should address the documentation error first.

**Comment by smckenzie23** [comment]
Amazon MQ does support these version. This is not meant to be a code string, and in every case where that is it uses "5.15.8" or similar. This is a document meant to list what engines it supports.

For instance "ActiveMQ 5.15.8 (recommended)" is not meant to be pasted into CloudFormation.
