### ISSUE TITLE
Rabbit MQ broker defaults typo?

### ISSUE THREAD

**Issue by dthvt** [awsdocs/amazon-mq-developer-guide#14]
The table at https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-defaults.html says max-length for a m5.xlarge cluster should be set to 90,000,000.  Given the other values in the table, it looks like that should be 9,000,000.

**Comment by fararmin** [comment]
Hi there,

Thank you for your feedback on the Amazon MQ for RabbitMQ defaults topic. We reviewed and verified that as you suspected, the value should be changed to 9,000,000 and not 90,000,000. The public document will be updated shortly.

You can also submit feedback directly on any documentation page by scrolling to the bottom of the page, and under **Did this page help you?**, choosing **Provide feedback**.

Cheer,
Armin.
