### ISSUE TITLE
Clarify that ActiveMQ supports only AMQP 1.0 and not AMQP 0.9.1

### ISSUE THREAD

**Issue by GoodMirek** [awsdocs/amazon-mq-developer-guide#4]
AMQP 1.0 is a completely different protocol, compared to AMQP 0.9.1.
AMQP 0.9.1 is the natively supported protocol for RabbitMQ, which much higher deployment rate compared to AMQP 1.0.

It is not possible to use ActiveMQ as 1:1 replacement for RabbitMQ for most use cases, because most deployments of RabbitMQ use AMQP 0.9.1, while ActiveMQ supports only AMQP 1.0.
This is confirmed in a topic here: https://forums.aws.amazon.com/thread.jspa?threadID=268936
Unfortunately, this is not clear from the AWS MQ doc and requires some extended study of Apache docs.

It will be great if AWS MQ documentation can highlight that only AMQP 1.0 is supported and AMQP 0.9.1 is not.

**Comment by fararmin** [comment]
Hi there,

Thank you for your feedback. We always welcome and encourage feedback to help us improve our documentation. We are working hard on a set of improvements to the Amazon MQ documentation which will address the supported AMQP protocols among other topics. I'm closing this issue as it is currently being addressed.

Thank you.
